---
title: "Restaurant Inspection Review - Manhattan"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
data(rest_inspec)

rest_inspec =
  rest_inspec %>%
  filter(grade %in% c("A", "B", "C") & boro == "MANHATTAN") %>% 
  mutate(
    boro = str_to_title(boro), 
    cuisine_description = recode(cuisine_description,
      "Café/Coffee/Tea" = "Cafe/Coffee/Tea", 
      "Latin (Cuban, Dominican, Puerto Rican, South & Central American)" = "Latin")) %>% 
  select(boro, grade, score, cuisine_description, building, zipcode)

top_cuisines = rest_inspec %>% 
  count(cuisine_description, sort = TRUE) %>% 
  top_n(10) %>% 
  select(cuisine_description, n)


figure2 = inner_join(rest_inspec, top_cuisines, by = "cuisine_description") %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) %>% 
  plot_ly(x = ~cuisine_description, y = ~score, color = ~cuisine_description, type = "box",
          colors = "Set2") 

figure3 = rest_inspec %>% 
  count(cuisine_description) %>% 
  filter(n >= 1500) %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) %>% 
  plot_ly(x = ~cuisine_description, y = ~n, color = ~cuisine_description, type = "bar")

figure4 = rest_inspec %>% 
  group_by(cuisine_description, grade) %>% 
  summarize(mean_score = mean(score)) %>% 
  plot_ly(x = ~cuisine_description, y = ~mean_score, color = ~grade, type = "scatter", mode = "markers")
```

Column {data-width=600}
-----------------------------------------------------------------------
### Average Scores by Grade and Cuisine
```{r}
figure4
```


Column {data-width=400}
-----------------------------------------------------------------------

### Counts by Cuisine  (over 1,500)

```{r}
figure3
```


### Spread of Scores by Top 10 Cuisines
```{r}
figure2
```




