---
title: "Academic Projects"
output:
  html_document: 
    toc: false
    toc_float: false
---

Below are projects completed at Columbia University Mailman School of Public Health. 

**SAS OnDemand**:   

* Social Support and HIV Testing Frequency Among Black MSM and TGW in NYC (*Thesis: in progress*)  
  + Methods: Multinomial Logistic Regression

* Association between Self-Identified Sexual Orientation and Diagnosis of STIs Modified by Sex: A Cross Sectional Study ([abstract](data/Sexual Orientation and STI Abstract.pdf), [code](data/Sexual Orientation and STI Code.sas))  
  + Methods: Multivariable Logistic Regression


**RStudio**: 

* Climate Change and Natural Disasters in the United States ([website](https://ilz2105.github.io/disasters.github.io/), [GitHub](https://github.com/ilz2105/disasters.github.io))  
  + Methods: Poisson Regression with Cross Validation
  + Packages: Shiny, plotly, tidyverse, ggplot

**QGIS**: 

* Effects of Wildfire Frequency and Intensity on Asthma Related
Emergency Department Visits in California from 2008-2017 ([poster](data/Wildfires and Asthma.pdf))  
  + Methods: Spatial clustering, OLS regression



